apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: phfupl2je-python 
  janus-idp.io/tekton: phfupl2je-python
  backstage.io/kubernetes-id: phfupl2je-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: phfupl2je-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml